/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KennyHakaj
 */
public class priceAdjustment extends javax.swing.JFrame {

    /**
     * Creates new form priceAdjustment
     */
    public priceAdjustment() {
        initComponents();
        dropDown();
        oldPrice.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        paBar = new javax.swing.JComboBox<>();
        oldPrice = new javax.swing.JTextField();
        newPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        menuBar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        menuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarActionPerformed(evt);
            }
        });
        menuBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                menuBarPropertyChange(evt);
            }
        });
        menuBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuBarKeyPressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        paBar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        paBar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paBarItemStateChanged(evt);
            }
        });
        paBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paBarFocusGained(evt);
            }
        });
        paBar.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                paBarPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                paBarPopupMenuWillBecomeVisible(evt);
            }
        });
        paBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paBarMouseEntered(evt);
            }
        });
        paBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paBarActionPerformed(evt);
            }
        });
        paBar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                paBarPropertyChange(evt);
            }
        });
        paBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paBarKeyPressed(evt);
            }
        });

        jLabel1.setText("Item");

        jLabel2.setText("Old Price");

        jLabel3.setText("New Price");

        jButton1.setText("Adjust");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(paBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(newPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection con;
    PreparedStatement pst,me,pst2;
    ResultSet rs,ms,fu;
    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        settingsMenu obj = new settingsMenu();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
 public void dropDown(){
    
        
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salepos","root","pizza712");
            me=con.prepareStatement("select * from sales");
        
            
       
           
                paBar.removeAllItems();

                ms = me.executeQuery();

                while(ms.next()){
                    paBar.addItem(ms.getString("product"));
                    
                }

         
           return;
            
            
          

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(posDineIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(posDineIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    private void menuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarActionPerformed

    private void menuBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_menuBarPropertyChange

    }//GEN-LAST:event_menuBarPropertyChange

    private void menuBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuBarKeyPressed

    }//GEN-LAST:event_menuBarKeyPressed

    private void paBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paBarActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_paBarActionPerformed

    private void paBarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_paBarPropertyChange
     
    }//GEN-LAST:event_paBarPropertyChange

    public void putOldPrice(){
    
    
    String code = paBar.getSelectedItem().toString();
       

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salepos","root","pizza712");
            pst=con.prepareStatement("select * from sales where Product = ?");

          
            pst.setString(1,code);

            rs= pst.executeQuery();

            

           if(rs.next() == false){
                
                    JOptionPane.showMessageDialog(this, "Error");
                    
                }
                else
                {
                String x=rs.getString("price");
                oldPrice.setText(x.trim());
                }
            return;

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(posDineIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
        }     
    
    }
    
    
    private void paBarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paBarKeyPressed

    }//GEN-LAST:event_paBarKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String code = paBar.getSelectedItem().toString();
        String np= newPrice.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/salepos","root","pizza712");
            pst=con.prepareStatement("update sales set price =? where product = ?");

            //UPDATE `salepos`.`sales` SET `Price` = '20' WHERE (`Product` = 'Spaghetti');
            
            pst.setString(1,np);
            pst.setString(2,code);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Success!");
            
            oldPrice.setText("");
            newPrice.setText("");

            return;

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(posDineIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(posDineIn.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void paBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paBarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_paBarFocusGained

    private void paBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paBarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_paBarMouseClicked

    private void paBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paBarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_paBarMouseEntered

    private void paBarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paBarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_paBarItemStateChanged

    private void paBarPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_paBarPopupMenuWillBecomeVisible
putOldPrice();         // TODO add your handling code here:
    }//GEN-LAST:event_paBarPopupMenuWillBecomeVisible

    private void paBarPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_paBarPopupMenuWillBecomeInvisible
putOldPrice();         // TODO add your handling code here:
    }//GEN-LAST:event_paBarPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(priceAdjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(priceAdjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(priceAdjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(priceAdjustment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new priceAdjustment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> menuBar;
    private javax.swing.JTextField newPrice;
    private javax.swing.JTextField oldPrice;
    private javax.swing.JComboBox<String> paBar;
    // End of variables declaration//GEN-END:variables
}
