/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sales;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author KennyHakaj
 */
public class tableNumber extends javax.swing.JFrame {

    /**
     * Creates new form tableNumber
     */
    public tableNumber() {
        initComponents();
    }
    register reg = new register();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("New Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Current Table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton2)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        orderFrame obj = new orderFrame();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JTextField jpf = new JTextField(24);
        JLabel jl = new JLabel("Enter Table Number: ");
        Box box = Box.createHorizontalBox();
        box.add(jl);
        box.add(jpf);
        
        
        int x = new JOptionPane().showConfirmDialog(null,box,"Table entry",JOptionPane.OK_CANCEL_OPTION);
        
                if(x== JOptionPane.CANCEL_OPTION){
        return;
        }else if(x== JOptionPane.OK_OPTION){
        int tableNum = Integer.parseInt(jpf.getText());
        
        if(reg.checkAvailible(tableNum)==false){
        
            JOptionPane.showMessageDialog(this, "Table is being used!");
            return;
        
        }else{
           this.dispose();
           newPosdinein obj = new newPosdinein();
           obj.addTableNum(tableNum);
           obj.setVisible(true);
        }
           
        }
         
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame("New Frame");
        
        f.setLocation(100, 150);
   //make sure it quits when x is clicked
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         //set look and feel
        f.setDefaultLookAndFeelDecorated(true);
        f.setLocationRelativeTo(null);
        int[] takenTables= reg.takenTables();
        
        f.setSize(500,500);
        int buttonCount=0;
        int oneCount=0;
        
        if(takenTables[0]==0){
            JOptionPane.showMessageDialog(this, "No Tables are being used!");
            return;
        }else{
        
        for(int i=0;i<takenTables.length;i++){

            if(takenTables[i]!=0){ 
            int x= takenTables[i];
            //if(takenTables[i]==1){oneCount++;}
            
            String button = ""+takenTables[i];
            
            JButton b = new JButton(button);
            
            b.setBounds(20+(buttonCount*40),20,40,40);
            
            
             b.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
             
            orderMod obj = new orderMod();
            
            String a=reg.getTableOrder(x);
            
             String cutLastLine=a.substring(0,a.lastIndexOf("\n"));
        
             String tick= cutLastLine.substring(a.lastIndexOf("#")+1);
             
             int t = Integer.parseInt(tick);
            
            obj.setReceiptText(reg.getOrder(t));
            
            obj.tableNum(x);
            
            obj.setVisible(true);
            f.dispose();
           
            
         }
      });
            this.dispose();
            f.add(b);
            buttonCount++;
            
            }
            
        
        }
        
       // JButton b = new JButton(""+oneCount);
       // f.add(b);
        f.setLayout(null);
        f.setVisible(true);
        
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
